### ISSUE TITLE
Video from the presentation

### ISSUE THREAD

**Issue by iSapozhnik** [fdiaz/swiftable-2019#1]
Hey @fdiaz! I'm curious is there a link to the video from the presentation?
Thanks in advance!

**Comment by fdiaz** [comment]
Hi @iSapozhnik 

There is one [here](https://youtu.be/KhZcSRXJHFs).

I'd also recommend [this article](https://medium.com/airbnb-engineering/designing-for-productivity-in-a-large-scale-ios-application-9376a430a0bf) written by a coworker about some of the same ideas.

**Comment by iSapozhnik** [comment]
Many thanks!
